### PR TITLE
⬆️ Update dependency for React@^17.0.2

### PR DESCRIPTION
**Pull request by productiveme**
## Description
React updated to 17.0.2

## Motivation and Context
It causes dependency issues with latest gatsby

## How Has This Been Tested?
`npm t` passes all tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING.md**](./docs/CONTRIBUTING.md) document.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by KRRISH96** [comment]
@productiveme any specific issue for closing this?

**Comment by productiveme** [comment]
I don't think its needed to require latest react, my issue was a problem with dependency resolution between React 16, 17.0.1 and 17.0.2 and after testing with this plugin on a higher version, I still have other conflicts between plugins. Seems this is the wrong avenue to resolve the problem.

**Comment by KRRISH96** [comment]
Got it!

same kind of issue here, many of our deep dependencies require react v16.x and the new tech we wanna try supports only react v17 or above.

So, thought an upgrade of all deps and their deep deps should solve it (unfortunately none has react v17 supported yet)🤞

though this won't solve the conflicts, I would still suggest to keep this open as this has to be done sooner or later.

**Comment by tterb** [comment]
Ideally, we would want the package to support both v16 and v17. 
So the `peerDependency` would be something like:
```
"react":  "^16.0.0 || ^17.0.0"
```

**Pull request closed without merging**
